/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simpurna.view;

import java.awt.event.MouseEvent;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import simpurna.controller.KamarController;
import simpurna.controller.UserController;

/**
 *
 * @author alfia
 */
public class AddRenter extends javax.swing.JPanel {

    /**
     * Creates new form AddRenter
     */
    KamarController kc = new KamarController();
    UserController uc = new UserController();
    public AddRenter() {
        initComponents();
        kc.setKamarKosong(this);
        uc.displayUsersInsertedThisYear(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormAddRenter = new javax.swing.JPanel();
        judulRincian1 = new javax.swing.JLabel();
        labelJenisHewan = new javax.swing.JLabel();
        labelRasHewan = new javax.swing.JLabel();
        labelJenisKelamin = new javax.swing.JLabel();
        labelTanggalLahir = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        labelTanggalLahir1 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        kontakTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        alamatTextField = new javax.swing.JTextField();
        kamarComboBox = new javax.swing.JComboBox<>();
        panelRincian = new javax.swing.JPanel();
        judulRincian = new javax.swing.JLabel();
        jScrollRincian = new javax.swing.JScrollPane();
        rincianPenghuniSetahunTerakhir = new javax.swing.JTable();
        homeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFormAddRenter.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelFormAddRenter.setPreferredSize(new java.awt.Dimension(277, 134));

        judulRincian1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulRincian1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulRincian1.setText("Tambah Penghuni");

        labelJenisHewan.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelJenisHewan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJenisHewan.setText("Username");

        labelRasHewan.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelRasHewan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRasHewan.setText("Nama");

        labelJenisKelamin.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelJenisKelamin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJenisKelamin.setText("Alamat");

        labelTanggalLahir.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelTanggalLahir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTanggalLahir.setText("Nomor Telepon");

        submitButton.setBackground(new java.awt.Color(204, 204, 204));
        submitButton.setText("SUBMIT");
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        labelTanggalLahir1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelTanggalLahir1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTanggalLahir1.setText("Kamar");

        kamarComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelFormAddRenterLayout = new javax.swing.GroupLayout(panelFormAddRenter);
        panelFormAddRenter.setLayout(panelFormAddRenterLayout);
        panelFormAddRenterLayout.setHorizontalGroup(
            panelFormAddRenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormAddRenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulRincian1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelFormAddRenterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelFormAddRenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(submitButton)
                    .addComponent(labelTanggalLahir1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTanggalLahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJenisKelamin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRasHewan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJenisHewan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kontakTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kamarComboBox, 0, 252, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelFormAddRenterLayout.setVerticalGroup(
            panelFormAddRenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormAddRenterLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(judulRincian1)
                .addGap(12, 12, 12)
                .addComponent(labelJenisHewan)
                .addGap(1, 1, 1)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRasHewan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJenisKelamin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTanggalLahir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kontakTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTanggalLahir1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kamarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitButton)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        add(panelFormAddRenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 290, 400));

        panelRincian.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelRincian.setPreferredSize(new java.awt.Dimension(277, 134));

        judulRincian.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulRincian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulRincian.setText("Penghuni Baru Setahun Terakhir");

        rincianPenghuniSetahunTerakhir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "Kontak", "Tanggal Masuk", "Kamar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rincianPenghuniSetahunTerakhir.setRowHeight(30);
        rincianPenghuniSetahunTerakhir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rincianPenghuniSetahunTerakhirMouseClicked(evt);
            }
        });
        jScrollRincian.setViewportView(rincianPenghuniSetahunTerakhir);

        javax.swing.GroupLayout panelRincianLayout = new javax.swing.GroupLayout(panelRincian);
        panelRincian.setLayout(panelRincianLayout);
        panelRincianLayout.setHorizontalGroup(
            panelRincianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulRincian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRincianLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollRincian, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelRincianLayout.setVerticalGroup(
            panelRincianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincianLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(judulRincian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollRincian, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        add(panelRincian, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 520, 400));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/home.png"))); // NOI18N
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        uc.insertUsers(this);
        uc.displayUsersInsertedThisYear(this);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        DashboardAdmin da = new DashboardAdmin();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(da);

        parentWindow.pack();

        da.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void rincianPenghuniSetahunTerakhirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rincianPenghuniSetahunTerakhirMouseClicked
        // TODO add your handling code here:
         if (evt.getButton() == MouseEvent.BUTTON1) { // Check if left mouse button is pressed
            int selectedRow = rincianPenghuniSetahunTerakhir.getSelectedRow();
            if (selectedRow >= 0) {
                String nama = rincianPenghuniSetahunTerakhir.getValueAt(selectedRow, 0).toString();
                String alamat = rincianPenghuniSetahunTerakhir.getValueAt(selectedRow, 1).toString();
                String kontak = rincianPenghuniSetahunTerakhir.getValueAt(selectedRow, 2).toString();
                String tgl = rincianPenghuniSetahunTerakhir.getValueAt(selectedRow, 3).toString();
                String kamar = rincianPenghuniSetahunTerakhir.getValueAt(selectedRow, 4).toString();

                JOptionPane.showMessageDialog(this, "Nama: " + nama + "\nAlamat: " + alamat + "\nKontak: " + kontak + "\nTanggal Masuk: " + tgl + "\nNo Kamar: " + kamar, "Detail Data", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_rincianPenghuniSetahunTerakhirMouseClicked
    
    public JComboBox getKamarKosong() {
        return kamarComboBox;
    }

    public JTable getTableAddRenter() {
        return rincianPenghuniSetahunTerakhir;
    }
    
    public JTextField getUsername() {
        return usernameTextField;
    }
    
    public JTextField getNameUser() {
        return namaTextField;
    }
    
    public JTextField getAlamat() {
        return alamatTextField;
    }
    
    public JTextField getKontak() {
        return kontakTextField;
    }
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatTextField;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollRincian;
    private javax.swing.JLabel judulRincian;
    private javax.swing.JLabel judulRincian1;
    private javax.swing.JComboBox<String> kamarComboBox;
    private javax.swing.JTextField kontakTextField;
    private javax.swing.JLabel labelJenisHewan;
    private javax.swing.JLabel labelJenisKelamin;
    private javax.swing.JLabel labelRasHewan;
    private javax.swing.JLabel labelTanggalLahir;
    private javax.swing.JLabel labelTanggalLahir1;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JPanel panelFormAddRenter;
    private javax.swing.JPanel panelRincian;
    private javax.swing.JTable rincianPenghuniSetahunTerakhir;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
