/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simpurna.view;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import simpurna.controller.KamarController;

/**
 *
 * @author alfia
 */
public class CekKamar extends javax.swing.JPanel {

    /**
     * Creates new form CekKamar
     */
    KamarController kamarController = new KamarController();
    public CekKamar() {
        initComponents();
        kamarController.displayKamarEksklusif(this);
        kamarController.displayKamarReguler(this);
        kamarController.countJmlPenghuniEks(this);
        kamarController.countJmlPenghuniReg(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeButton = new javax.swing.JButton();
        panelRincian1 = new javax.swing.JPanel();
        judulRincian1 = new javax.swing.JLabel();
        jScrollRincian1 = new javax.swing.JScrollPane();
        eksklusifTable = new javax.swing.JTable();
        judulRincian2 = new javax.swing.JLabel();
        kapasitasEksLabel = new javax.swing.JLabel();
        panelRincian = new javax.swing.JPanel();
        judulRincian = new javax.swing.JLabel();
        jScrollRincian = new javax.swing.JScrollPane();
        regulerTable = new javax.swing.JTable();
        judulRincian4 = new javax.swing.JLabel();
        kapasitasRegLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/home.png"))); // NOI18N
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 60, 60));

        panelRincian1.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelRincian1.setPreferredSize(new java.awt.Dimension(277, 134));

        judulRincian1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulRincian1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulRincian1.setText("Rincian Kamar Eksklusif");

        eksklusifTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Kamar", "Status", "Penyewa", "Harga Sewa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eksklusifTable.setRowHeight(30);
        eksklusifTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eksklusifTableMouseClicked(evt);
            }
        });
        jScrollRincian1.setViewportView(eksklusifTable);

        judulRincian2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        judulRincian2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        judulRincian2.setText("Kapasitas Eksklusif Tersedia:");

        kapasitasEksLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        kapasitasEksLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kapasitasEksLabel.setText("100");

        javax.swing.GroupLayout panelRincian1Layout = new javax.swing.GroupLayout(panelRincian1);
        panelRincian1.setLayout(panelRincian1Layout);
        panelRincian1Layout.setHorizontalGroup(
            panelRincian1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincian1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRincian1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRincian1Layout.createSequentialGroup()
                        .addComponent(judulRincian1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelRincian1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelRincian1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollRincian1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRincian1Layout.createSequentialGroup()
                                .addComponent(judulRincian2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kapasitasEksLabel)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelRincian1Layout.setVerticalGroup(
            panelRincian1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincian1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(judulRincian1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollRincian1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRincian1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judulRincian2)
                    .addComponent(kapasitasEksLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelRincian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 370, 380));

        panelRincian.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelRincian.setPreferredSize(new java.awt.Dimension(277, 134));

        judulRincian.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulRincian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulRincian.setText("Rincian Kamar Reguler");

        regulerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Kamar", "Status", "Penyewa", "Harga Sewa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        regulerTable.setRowHeight(30);
        regulerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regulerTableMouseClicked(evt);
            }
        });
        jScrollRincian.setViewportView(regulerTable);

        judulRincian4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        judulRincian4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        judulRincian4.setText("Kapasitas Reguler Tersedia:");

        kapasitasRegLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        kapasitasRegLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kapasitasRegLabel.setText("100");

        javax.swing.GroupLayout panelRincianLayout = new javax.swing.GroupLayout(panelRincian);
        panelRincian.setLayout(panelRincianLayout);
        panelRincianLayout.setHorizontalGroup(
            panelRincianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRincianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRincianLayout.createSequentialGroup()
                        .addComponent(judulRincian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelRincianLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelRincianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRincianLayout.createSequentialGroup()
                                .addComponent(judulRincian4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kapasitasRegLabel))
                            .addComponent(jScrollRincian, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelRincianLayout.setVerticalGroup(
            panelRincianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulRincian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollRincian, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRincianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judulRincian4)
                    .addComponent(kapasitasRegLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelRincian, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 370, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 912, 506));
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        DashboardAdmin da = new DashboardAdmin();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(da);

        parentWindow.pack();

        da.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void regulerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regulerTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = regulerTable.getSelectedRow();
        if (selectedRow >= 0) {
            String noKamar = regulerTable.getValueAt(selectedRow, 0).toString();
            String status = regulerTable.getValueAt(selectedRow, 1).toString();
            String penyewa = regulerTable.getValueAt(selectedRow, 2).toString();
            String hargaSewa = regulerTable.getValueAt(selectedRow, 3).toString();

            // Perform the desired action with the clicked row data
            // For example, you can display the data in a dialog box
            JOptionPane.showMessageDialog(this, "No Kamar: " + noKamar + "\nStatus: " + status + "\nPenyewa: " + penyewa + "\nHarga Sewa: " + hargaSewa);
            regulerTable.clearSelection();
        }
    }//GEN-LAST:event_regulerTableMouseClicked

    private void eksklusifTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eksklusifTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = eksklusifTable.getSelectedRow();
        if (selectedRow >= 0) {
            String noKamar = eksklusifTable.getValueAt(selectedRow, 0).toString();
            String status = eksklusifTable.getValueAt(selectedRow, 1).toString();
            String penyewa = eksklusifTable.getValueAt(selectedRow, 2).toString();
            String hargaSewa = eksklusifTable.getValueAt(selectedRow, 3).toString();

            // Perform the desired action with the clicked row data
            // For example, you can display the data in a dialog box
            JOptionPane.showMessageDialog(this, "No Kamar: " + noKamar + "\nStatus: " + status + "\nPenyewa: " + penyewa + "\nHarga Sewa: " + hargaSewa);
            eksklusifTable.clearSelection();
        }
    }//GEN-LAST:event_eksklusifTableMouseClicked
    
    public JTable getEksklusifTable() {
        return eksklusifTable;
    }

    public JTable getRegulerTable() {
        return regulerTable;
    }
    
    public JLabel getKapasitasEks() {
        return kapasitasEksLabel;
    }
    
    public JLabel getKapasitasReg() {
        return kapasitasRegLabel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable eksklusifTable;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollRincian;
    private javax.swing.JScrollPane jScrollRincian1;
    private javax.swing.JLabel judulRincian;
    private javax.swing.JLabel judulRincian1;
    private javax.swing.JLabel judulRincian2;
    private javax.swing.JLabel judulRincian4;
    private javax.swing.JLabel kapasitasEksLabel;
    private javax.swing.JLabel kapasitasRegLabel;
    private javax.swing.JPanel panelRincian;
    private javax.swing.JPanel panelRincian1;
    private javax.swing.JTable regulerTable;
    // End of variables declaration//GEN-END:variables
}
