/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simpurna.view;

import javax.swing.JButton;
import javax.swing.ToolTipManager;

/**
 *
 * @author alfia
 */
public class DashboardAdmin extends javax.swing.JPanel {

    /**
     * Creates new form dashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDashboard = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        beliButton = new javax.swing.JButton();
        jualButton = new javax.swing.JButton();
        breedButton = new javax.swing.JButton();
        listHewanButton = new javax.swing.JButton();
        listPegawaiButton = new javax.swing.JButton();
        gajiPegawaiButton = new javax.swing.JButton();
        cekPengeluaranButton = new javax.swing.JButton();
        beriMakanButton = new javax.swing.JButton();
        beriVaksinButton = new javax.swing.JButton();
        beriObatButton = new javax.swing.JButton();
        cekKapasitasButton = new javax.swing.JButton();
        panelHewanSiapJual = new javax.swing.JPanel();
        judulHewanSiapJual = new javax.swing.JLabel();
        gambarHewanSiapJual = new javax.swing.JLabel();
        kambingSiapJual = new javax.swing.JLabel();
        sapiSiapJual = new javax.swing.JLabel();
        dombaSiapJual = new javax.swing.JLabel();
        panelJumlahHewan = new javax.swing.JPanel();
        judulJumlahHewan = new javax.swing.JLabel();
        gambarJumlahHewan = new javax.swing.JLabel();
        jumlahDomba = new javax.swing.JLabel();
        jumlahSapi = new javax.swing.JLabel();
        jumlahKambing = new javax.swing.JLabel();
        panelTotalPengeluaran = new javax.swing.JPanel();
        judulTotalPengeluaran = new javax.swing.JLabel();
        totalPengeluaran = new javax.swing.JLabel();
        panelHewanButuhTindakan = new javax.swing.JPanel();
        judulHewanButuhTindakan = new javax.swing.JLabel();
        gambarHewanSiapJual1 = new javax.swing.JLabel();
        sapiButuhTindakan = new javax.swing.JLabel();
        kambingButuhTindakan = new javax.swing.JLabel();
        dombaButuhTindakan = new javax.swing.JLabel();
        akunButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDashboard.setBackground(new java.awt.Color(221, 241, 247, 200));
        panelDashboard.setPreferredSize(new java.awt.Dimension(209, 500));

        judul.setFont(new java.awt.Font("Cooper Black", 1, 23)); // NOI18N
        judul.setText("VRINFARM");

        beliButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        beliButton.setText("BELI");
        beliButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beliButton.setMaximumSize(new java.awt.Dimension(146, 26));
        beliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliButtonActionPerformed(evt);
            }
        });

        jualButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jualButton.setText("JUAL");
        jualButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jualButton.setMaximumSize(new java.awt.Dimension(146, 26));
        jualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jualButtonActionPerformed(evt);
            }
        });

        breedButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        breedButton.setText("BREED");
        breedButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        breedButton.setMaximumSize(new java.awt.Dimension(146, 26));
        breedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breedButtonActionPerformed(evt);
            }
        });

        listHewanButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        listHewanButton.setText("LIST HEWAN");
        listHewanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listHewanButton.setMaximumSize(new java.awt.Dimension(146, 26));
        listHewanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listHewanButtonActionPerformed(evt);
            }
        });

        listPegawaiButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        listPegawaiButton.setText("LIST PEGAWAI");
        listPegawaiButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listPegawaiButton.setMaximumSize(new java.awt.Dimension(146, 26));
        listPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPegawaiButtonActionPerformed(evt);
            }
        });

        gajiPegawaiButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        gajiPegawaiButton.setText("GAJI PEGAWAI");
        gajiPegawaiButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gajiPegawaiButton.setMaximumSize(new java.awt.Dimension(146, 26));
        gajiPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajiPegawaiButtonActionPerformed(evt);
            }
        });

        cekPengeluaranButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cekPengeluaranButton.setText("CEK PENGELUARAN");
        cekPengeluaranButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cekPengeluaranButton.setMaximumSize(new java.awt.Dimension(146, 26));
        cekPengeluaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekPengeluaranButtonActionPerformed(evt);
            }
        });

        beriMakanButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        beriMakanButton.setText("BERI MAKAN");
        beriMakanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beriMakanButton.setMaximumSize(new java.awt.Dimension(146, 26));
        beriMakanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beriMakanButtonActionPerformed(evt);
            }
        });

        beriVaksinButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        beriVaksinButton.setText("BERI VAKSIN");
        beriVaksinButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beriVaksinButton.setMaximumSize(new java.awt.Dimension(146, 26));
        beriVaksinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beriVaksinButtonActionPerformed(evt);
            }
        });

        beriObatButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        beriObatButton.setText("BERI PERAWATAN");
        beriObatButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beriObatButton.setMaximumSize(new java.awt.Dimension(146, 26));
        beriObatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beriObatButtonActionPerformed(evt);
            }
        });

        cekKapasitasButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cekKapasitasButton.setText("CEK KAPASITAS");
        cekKapasitasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cekKapasitasButton.setMaximumSize(new java.awt.Dimension(146, 26));
        cekKapasitasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKapasitasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beliButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jualButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(breedButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listHewanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listPegawaiButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gajiPegawaiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cekPengeluaranButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beriMakanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beriVaksinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beriObatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cekKapasitasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(beliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(breedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listHewanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listPegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gajiPegawaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cekPengeluaranButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beriMakanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beriVaksinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beriObatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cekKapasitasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 209, 500));

        panelHewanSiapJual.setBackground(new java.awt.Color(221, 241, 247, 200));
        panelHewanSiapJual.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        panelHewanSiapJual.setPreferredSize(new java.awt.Dimension(277, 199));

        judulHewanSiapJual.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulHewanSiapJual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulHewanSiapJual.setText("Hewan Siap Jual");
        judulHewanSiapJual.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        kambingSiapJual.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        kambingSiapJual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kambingSiapJual.setText("07");

        sapiSiapJual.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        sapiSiapJual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sapiSiapJual.setText("01");

        dombaSiapJual.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        dombaSiapJual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dombaSiapJual.setText("10");

        javax.swing.GroupLayout panelHewanSiapJualLayout = new javax.swing.GroupLayout(panelHewanSiapJual);
        panelHewanSiapJual.setLayout(panelHewanSiapJualLayout);
        panelHewanSiapJualLayout.setHorizontalGroup(
            panelHewanSiapJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judulHewanSiapJual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHewanSiapJualLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(sapiSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(dombaSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(kambingSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(panelHewanSiapJualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gambarHewanSiapJual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHewanSiapJualLayout.setVerticalGroup(
            panelHewanSiapJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHewanSiapJualLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(judulHewanSiapJual)
                .addGap(18, 18, 18)
                .addComponent(gambarHewanSiapJual)
                .addGap(10, 10, 10)
                .addGroup(panelHewanSiapJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sapiSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dombaSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kambingSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        add(panelHewanSiapJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 270, -1));

        panelJumlahHewan.setBackground(new java.awt.Color(221, 241, 247, 200));
        panelJumlahHewan.setPreferredSize(new java.awt.Dimension(277, 199));

        judulJumlahHewan.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulJumlahHewan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulJumlahHewan.setText("Jumlah Hewan");

        jumlahDomba.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jumlahDomba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahDomba.setText("99");

        jumlahSapi.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jumlahSapi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahSapi.setText("38");

        jumlahKambing.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jumlahKambing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahKambing.setText("56");

        javax.swing.GroupLayout panelJumlahHewanLayout = new javax.swing.GroupLayout(panelJumlahHewan);
        panelJumlahHewan.setLayout(panelJumlahHewanLayout);
        panelJumlahHewanLayout.setHorizontalGroup(
            panelJumlahHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJumlahHewanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJumlahHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJumlahHewanLayout.createSequentialGroup()
                        .addComponent(judulJumlahHewan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJumlahHewanLayout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(jumlahSapi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jumlahDomba, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jumlahKambing, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(panelJumlahHewanLayout.createSequentialGroup()
                        .addComponent(gambarJumlahHewan)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelJumlahHewanLayout.setVerticalGroup(
            panelJumlahHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJumlahHewanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(judulJumlahHewan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gambarJumlahHewan)
                .addGap(12, 12, 12)
                .addGroup(panelJumlahHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahSapi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahDomba, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahKambing, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        add(panelJumlahHewan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        panelTotalPengeluaran.setBackground(new java.awt.Color(221, 241, 247, 200));
        panelTotalPengeluaran.setPreferredSize(new java.awt.Dimension(277, 134));

        judulTotalPengeluaran.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulTotalPengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulTotalPengeluaran.setText("Total Pengeluaran");

        totalPengeluaran.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        totalPengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPengeluaran.setText("Rp 1.000.000");

        javax.swing.GroupLayout panelTotalPengeluaranLayout = new javax.swing.GroupLayout(panelTotalPengeluaran);
        panelTotalPengeluaran.setLayout(panelTotalPengeluaranLayout);
        panelTotalPengeluaranLayout.setHorizontalGroup(
            panelTotalPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judulTotalPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalPengeluaranLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(totalPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        panelTotalPengeluaranLayout.setVerticalGroup(
            panelTotalPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalPengeluaranLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(judulTotalPengeluaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        add(panelTotalPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, -1, 170));

        panelHewanButuhTindakan.setBackground(new java.awt.Color(221, 241, 247, 200));
        panelHewanButuhTindakan.setPreferredSize(new java.awt.Dimension(277, 134));

        judulHewanButuhTindakan.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulHewanButuhTindakan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulHewanButuhTindakan.setText("Hewan Butuh Tindakan");

        sapiButuhTindakan.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        sapiButuhTindakan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sapiButuhTindakan.setText("01");

        kambingButuhTindakan.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        kambingButuhTindakan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kambingButuhTindakan.setText("01");

        dombaButuhTindakan.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        dombaButuhTindakan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dombaButuhTindakan.setText("01");

        javax.swing.GroupLayout panelHewanButuhTindakanLayout = new javax.swing.GroupLayout(panelHewanButuhTindakan);
        panelHewanButuhTindakan.setLayout(panelHewanButuhTindakanLayout);
        panelHewanButuhTindakanLayout.setHorizontalGroup(
            panelHewanButuhTindakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHewanButuhTindakanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulHewanButuhTindakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelHewanButuhTindakanLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(sapiButuhTindakan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(dombaButuhTindakan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kambingButuhTindakan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(panelHewanButuhTindakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelHewanButuhTindakanLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(gambarHewanSiapJual1)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );
        panelHewanButuhTindakanLayout.setVerticalGroup(
            panelHewanButuhTindakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHewanButuhTindakanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(judulHewanButuhTindakan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(panelHewanButuhTindakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sapiButuhTindakan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kambingButuhTindakan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dombaButuhTindakan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(panelHewanButuhTindakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelHewanButuhTindakanLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(gambarHewanSiapJual1)
                    .addContainerGap(115, Short.MAX_VALUE)))
        );

        add(panelHewanButuhTindakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 270, 170));

        akunButton.setBackground(new java.awt.Color(204, 204, 204));
        akunButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/profil (2).png"))); // NOI18N
        akunButton.setBorder(null);
        akunButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        akunButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                akunButtonMouseEntered(evt);
            }
        });
        akunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akunButtonActionPerformed(evt);
            }
        });
        add(akunButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 50, 50));

        logoutButton.setBackground(new java.awt.Color(204, 204, 204));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/logout.png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 50, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/background.jpg"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void beliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliButtonActionPerformed
        
    }//GEN-LAST:event_beliButtonActionPerformed

    private void jualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jualButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jualButtonActionPerformed

    private void breedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breedButtonActionPerformed

     
    }//GEN-LAST:event_breedButtonActionPerformed

    private void listHewanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listHewanButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_listHewanButtonActionPerformed

    private void listPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPegawaiButtonActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_listPegawaiButtonActionPerformed

    private void gajiPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajiPegawaiButtonActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_gajiPegawaiButtonActionPerformed

    private void cekPengeluaranButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekPengeluaranButtonActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_cekPengeluaranButtonActionPerformed

    private void beriMakanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beriMakanButtonActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_beriMakanButtonActionPerformed

    private void beriVaksinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beriVaksinButtonActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_beriVaksinButtonActionPerformed

    private void beriObatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beriObatButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_beriObatButtonActionPerformed

    private void cekKapasitasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekKapasitasButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cekKapasitasButtonActionPerformed

    private void akunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akunButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_akunButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_logoutButtonActionPerformed

    private void akunButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunButtonMouseEntered
        // TODO add your handling code here:
        JButton button = (JButton) evt.getSource();
        button.setToolTipText("Ke halaman profil");
        ToolTipManager.sharedInstance().setInitialDelay(0);
    }//GEN-LAST:event_akunButtonMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akunButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton beliButton;
    private javax.swing.JButton beriMakanButton;
    private javax.swing.JButton beriObatButton;
    private javax.swing.JButton beriVaksinButton;
    private javax.swing.JButton breedButton;
    private javax.swing.JButton cekKapasitasButton;
    private javax.swing.JButton cekPengeluaranButton;
    private javax.swing.JLabel dombaButuhTindakan;
    private javax.swing.JLabel dombaSiapJual;
    private javax.swing.JButton gajiPegawaiButton;
    private javax.swing.JLabel gambarHewanSiapJual;
    private javax.swing.JLabel gambarHewanSiapJual1;
    private javax.swing.JLabel gambarJumlahHewan;
    private javax.swing.JButton jualButton;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judulHewanButuhTindakan;
    private javax.swing.JLabel judulHewanSiapJual;
    private javax.swing.JLabel judulJumlahHewan;
    private javax.swing.JLabel judulTotalPengeluaran;
    private javax.swing.JLabel jumlahDomba;
    private javax.swing.JLabel jumlahKambing;
    private javax.swing.JLabel jumlahSapi;
    private javax.swing.JLabel kambingButuhTindakan;
    private javax.swing.JLabel kambingSiapJual;
    private javax.swing.JButton listHewanButton;
    private javax.swing.JButton listPegawaiButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelHewanButuhTindakan;
    private javax.swing.JPanel panelHewanSiapJual;
    private javax.swing.JPanel panelJumlahHewan;
    private javax.swing.JPanel panelTotalPengeluaran;
    private javax.swing.JLabel sapiButuhTindakan;
    private javax.swing.JLabel sapiSiapJual;
    private javax.swing.JLabel totalPengeluaran;
    // End of variables declaration//GEN-END:variables
}
