/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simpurna.view;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.ToolTipManager;
import simpurna.controller.LaporanController;
import simpurna.controller.PembayaranController;
import simpurna.controller.PerizinanController;
import simpurna.controller.UserController;
import simpurna.model.Session;

/**
 *
 * @author alfia
 */
public class DashboardAdmin extends javax.swing.JPanel {

    /**
     * Creates new form dashboardAdmin
     */
    UserController userController = new UserController();
    PembayaranController pembayaranController = new PembayaranController();
    PerizinanController perizinanController = new PerizinanController();
    LaporanController laporanController = new LaporanController();
    
    public DashboardAdmin() {
        initComponents();
        userController.countJmlPenghuni(this);
        pembayaranController.countPembayaranNeedConfirm(this);
        perizinanController.countPerizinanMasuk(this);
        laporanController.countTotalPelaporanAdmin(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDashboard = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        addRenterButton = new javax.swing.JButton();
        cekPembayaranButton = new javax.swing.JButton();
        cekKamarButton = new javax.swing.JButton();
        kontakPentingButton = new javax.swing.JButton();
        listPenghuniButton = new javax.swing.JButton();
        cekPerizinanButton = new javax.swing.JButton();
        buatPengumumanButton = new javax.swing.JButton();
        kelolaAdminButton = new javax.swing.JButton();
        pelaporanButton = new javax.swing.JButton();
        panelHewanSiapJual = new javax.swing.JPanel();
        judulHewanSiapJual = new javax.swing.JLabel();
        gambarHewanSiapJual = new javax.swing.JLabel();
        jumlahPenghuniLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelJumlahHewan = new javax.swing.JPanel();
        judulJumlahHewan = new javax.swing.JLabel();
        gambarJumlahHewan = new javax.swing.JLabel();
        pembayaranBaruLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelTotalPengeluaran = new javax.swing.JPanel();
        judulTotalPengeluaran = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pelaporanMasukLabel = new javax.swing.JLabel();
        panelHewanButuhTindakan = new javax.swing.JPanel();
        judulHewanButuhTindakan = new javax.swing.JLabel();
        gambarHewanSiapJual1 = new javax.swing.JLabel();
        perizinanMasukLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDashboard.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelDashboard.setPreferredSize(new java.awt.Dimension(209, 500));

        judul.setFont(new java.awt.Font("Cooper Black", 1, 23)); // NOI18N
        judul.setText("siMPURNA");

        addRenterButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        addRenterButton.setText("TAMBAH PENGHUNI");
        addRenterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addRenterButton.setMaximumSize(new java.awt.Dimension(146, 26));
        addRenterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRenterButtonActionPerformed(evt);
            }
        });

        cekPembayaranButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cekPembayaranButton.setText("CEK PEMBAYARAN");
        cekPembayaranButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cekPembayaranButton.setMaximumSize(new java.awt.Dimension(146, 26));
        cekPembayaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekPembayaranButtonActionPerformed(evt);
            }
        });

        cekKamarButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cekKamarButton.setText("CEK KAPASITAS");
        cekKamarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cekKamarButton.setMaximumSize(new java.awt.Dimension(146, 26));
        cekKamarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKamarButtonActionPerformed(evt);
            }
        });

        kontakPentingButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kontakPentingButton.setText("KONTAK PENTING");
        kontakPentingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kontakPentingButton.setMaximumSize(new java.awt.Dimension(146, 26));
        kontakPentingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontakPentingButtonActionPerformed(evt);
            }
        });

        listPenghuniButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        listPenghuniButton.setText("LIST PENGHUNI");
        listPenghuniButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listPenghuniButton.setMaximumSize(new java.awt.Dimension(146, 26));
        listPenghuniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPenghuniButtonActionPerformed(evt);
            }
        });

        cekPerizinanButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cekPerizinanButton.setText("CEK PERIZINAN");
        cekPerizinanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cekPerizinanButton.setMaximumSize(new java.awt.Dimension(146, 26));
        cekPerizinanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekPerizinanButtonActionPerformed(evt);
            }
        });

        buatPengumumanButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        buatPengumumanButton.setText("BUAT PENGUMUMAN");
        buatPengumumanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buatPengumumanButton.setMaximumSize(new java.awt.Dimension(146, 26));
        buatPengumumanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatPengumumanButtonActionPerformed(evt);
            }
        });

        kelolaAdminButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kelolaAdminButton.setText("KELOLA ADMIN");
        kelolaAdminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kelolaAdminButton.setMaximumSize(new java.awt.Dimension(146, 26));
        kelolaAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelolaAdminButtonActionPerformed(evt);
            }
        });

        pelaporanButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pelaporanButton.setText("CEK PELAPORAN");
        pelaporanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pelaporanButton.setMaximumSize(new java.awt.Dimension(146, 26));
        pelaporanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelaporanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addRenterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cekPembayaranButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cekKamarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kontakPentingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listPenghuniButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cekPerizinanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buatPengumumanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kelolaAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pelaporanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDashboardLayout.createSequentialGroup()
                        .addComponent(judul)
                        .addGap(8, 8, 8)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addRenterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listPenghuniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cekPembayaranButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cekKamarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cekPerizinanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pelaporanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buatPengumumanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kelolaAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kontakPentingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 209, 500));

        panelHewanSiapJual.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelHewanSiapJual.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        panelHewanSiapJual.setPreferredSize(new java.awt.Dimension(277, 199));

        judulHewanSiapJual.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulHewanSiapJual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulHewanSiapJual.setText("Jumlah Penghuni");
        judulHewanSiapJual.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jumlahPenghuniLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jumlahPenghuniLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahPenghuniLabel.setText("07");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/penghuni.png"))); // NOI18N

        javax.swing.GroupLayout panelHewanSiapJualLayout = new javax.swing.GroupLayout(panelHewanSiapJual);
        panelHewanSiapJual.setLayout(panelHewanSiapJualLayout);
        panelHewanSiapJualLayout.setHorizontalGroup(
            panelHewanSiapJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judulHewanSiapJual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addGroup(panelHewanSiapJualLayout.createSequentialGroup()
                .addGroup(panelHewanSiapJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHewanSiapJualLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gambarHewanSiapJual)
                        .addGap(69, 69, 69)
                        .addComponent(jumlahPenghuniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHewanSiapJualLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHewanSiapJualLayout.setVerticalGroup(
            panelHewanSiapJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHewanSiapJualLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(judulHewanSiapJual)
                .addGroup(panelHewanSiapJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHewanSiapJualLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(gambarHewanSiapJual))
                    .addGroup(panelHewanSiapJualLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlahPenghuniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(panelHewanSiapJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 270, -1));

        panelJumlahHewan.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelJumlahHewan.setForeground(new java.awt.Color(255, 255, 255));
        panelJumlahHewan.setPreferredSize(new java.awt.Dimension(277, 199));

        judulJumlahHewan.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulJumlahHewan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulJumlahHewan.setText("Pembayaran Baru");

        pembayaranBaruLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        pembayaranBaruLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pembayaranBaruLabel.setText("56");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/pembayaran.png"))); // NOI18N

        javax.swing.GroupLayout panelJumlahHewanLayout = new javax.swing.GroupLayout(panelJumlahHewan);
        panelJumlahHewan.setLayout(panelJumlahHewanLayout);
        panelJumlahHewanLayout.setHorizontalGroup(
            panelJumlahHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJumlahHewanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJumlahHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJumlahHewanLayout.createSequentialGroup()
                        .addComponent(judulJumlahHewan, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJumlahHewanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pembayaranBaruLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(panelJumlahHewanLayout.createSequentialGroup()
                        .addComponent(gambarJumlahHewan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(106, 106, 106))))
        );
        panelJumlahHewanLayout.setVerticalGroup(
            panelJumlahHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJumlahHewanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(judulJumlahHewan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pembayaranBaruLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelJumlahHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJumlahHewanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(gambarJumlahHewan))
                    .addGroup(panelJumlahHewanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        add(panelJumlahHewan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        panelTotalPengeluaran.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelTotalPengeluaran.setPreferredSize(new java.awt.Dimension(277, 134));

        judulTotalPengeluaran.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulTotalPengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulTotalPengeluaran.setText("Total Pelaporan");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/complaint.png"))); // NOI18N

        pelaporanMasukLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        pelaporanMasukLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pelaporanMasukLabel.setText("56");

        javax.swing.GroupLayout panelTotalPengeluaranLayout = new javax.swing.GroupLayout(panelTotalPengeluaran);
        panelTotalPengeluaran.setLayout(panelTotalPengeluaranLayout);
        panelTotalPengeluaranLayout.setHorizontalGroup(
            panelTotalPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judulTotalPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTotalPengeluaranLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(pelaporanMasukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalPengeluaranLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(110, 110, 110))
        );
        panelTotalPengeluaranLayout.setVerticalGroup(
            panelTotalPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalPengeluaranLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judulTotalPengeluaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pelaporanMasukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(45, 45, 45))
        );

        add(panelTotalPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, 190));

        panelHewanButuhTindakan.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelHewanButuhTindakan.setPreferredSize(new java.awt.Dimension(277, 134));

        judulHewanButuhTindakan.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulHewanButuhTindakan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulHewanButuhTindakan.setText("Perizinan Masuk");

        perizinanMasukLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        perizinanMasukLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perizinanMasukLabel.setText("01");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/izin.png"))); // NOI18N

        javax.swing.GroupLayout panelHewanButuhTindakanLayout = new javax.swing.GroupLayout(panelHewanButuhTindakan);
        panelHewanButuhTindakan.setLayout(panelHewanButuhTindakanLayout);
        panelHewanButuhTindakanLayout.setHorizontalGroup(
            panelHewanButuhTindakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHewanButuhTindakanLayout.createSequentialGroup()
                .addGroup(panelHewanButuhTindakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHewanButuhTindakanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(judulHewanButuhTindakan, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                    .addGroup(panelHewanButuhTindakanLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelHewanButuhTindakanLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(perizinanMasukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelHewanButuhTindakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelHewanButuhTindakanLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(gambarHewanSiapJual1)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );
        panelHewanButuhTindakanLayout.setVerticalGroup(
            panelHewanButuhTindakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHewanButuhTindakanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judulHewanButuhTindakan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(perizinanMasukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(22, 22, 22))
            .addGroup(panelHewanButuhTindakanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelHewanButuhTindakanLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(gambarHewanSiapJual1)
                    .addContainerGap(145, Short.MAX_VALUE)))
        );

        add(panelHewanButuhTindakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 270, 190));

        logoutButton.setBackground(new java.awt.Color(204, 204, 204));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/logout.png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 50, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/background.jpg"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void addRenterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRenterButtonActionPerformed
        AddRenter ar = new AddRenter();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(ar);

        parentWindow.pack();
        
        parentWindow.setLocationRelativeTo(null);

        ar.setVisible(true);
    }//GEN-LAST:event_addRenterButtonActionPerformed

    private void cekPembayaranButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekPembayaranButtonActionPerformed
        // TODO add your handling code here:
        PembayaranAdmin pa = new PembayaranAdmin();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(pa);

        parentWindow.pack();
        
        parentWindow.setLocationRelativeTo(null);

        pa.setVisible(true);
    }//GEN-LAST:event_cekPembayaranButtonActionPerformed

    private void cekKamarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekKamarButtonActionPerformed
        CekKamar ck = new CekKamar();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(ck);

        parentWindow.pack();
        
        parentWindow.setLocationRelativeTo(null);

        ck.setVisible(true);
     
    }//GEN-LAST:event_cekKamarButtonActionPerformed

    private void kontakPentingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontakPentingButtonActionPerformed
        // TODO add your handling code here:
        KontakPentingAdmin kp = new KontakPentingAdmin();

        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(kp);

        parentWindow.pack();

        parentWindow.setLocationRelativeTo(null);

        kp.setVisible(true);

        
    }//GEN-LAST:event_kontakPentingButtonActionPerformed

    private void listPenghuniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPenghuniButtonActionPerformed
        // TODO add your handling code here:
        ListRenter listRenter= new ListRenter();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(listRenter);

        parentWindow.pack();
        
        parentWindow.setLocationRelativeTo(null);

        listRenter.setVisible(true);
    }//GEN-LAST:event_listPenghuniButtonActionPerformed

    private void cekPerizinanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekPerizinanButtonActionPerformed
        // TODO add your handling code here:
        PerizinanAdmin perizinanAdmin = new PerizinanAdmin();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(perizinanAdmin);

        parentWindow.pack();
        
        parentWindow.setLocationRelativeTo(null);

        perizinanAdmin.setVisible(true);
       
    }//GEN-LAST:event_cekPerizinanButtonActionPerformed

    private void buatPengumumanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatPengumumanButtonActionPerformed
        // TODO add your handling code here:
        PengumumanAdmin pa = new PengumumanAdmin();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(pa);

        parentWindow.pack();
        
        parentWindow.setLocationRelativeTo(null);

        pa.setVisible(true);
  
    }//GEN-LAST:event_buatPengumumanButtonActionPerformed

    private void kelolaAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelolaAdminButtonActionPerformed
        // TODO add your handling code here:
        ListAdmin la = new ListAdmin();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(la);

        parentWindow.pack();
        
        parentWindow.setLocationRelativeTo(null);

        la.setVisible(true);

    }//GEN-LAST:event_kelolaAdminButtonActionPerformed

    private void pelaporanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelaporanButtonActionPerformed
        // TODO add your handling code here:
        LaporanAdmin la = new LaporanAdmin();

        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(la);

        parentWindow.pack();

        parentWindow.setLocationRelativeTo(null);

        la.setVisible(true);

    }//GEN-LAST:event_pelaporanButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        Session session = Session.getInstance();
        session.clearSession();
        
        Login login = new Login();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.setVisible(false);
        
        login.setVisible(true);
        
        login.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        // TODO add your handling code here:
        JButton button = (JButton) evt.getSource();
        button.setToolTipText("Keluar");
        ToolTipManager.sharedInstance().setInitialDelay(0);
    }//GEN-LAST:event_logoutButtonMouseEntered
   
    public JLabel getJmlPenghuniLabel() {
        return jumlahPenghuniLabel;
    }
    
    public JLabel getPembayaranBaruLabel() {
        return pembayaranBaruLabel;
    }
    
    public JLabel getPerizinanMasuk() {
        return perizinanMasukLabel;
    }
    
    public JLabel getPelaporanMasuk() {
        return pelaporanMasukLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRenterButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton buatPengumumanButton;
    private javax.swing.JButton cekKamarButton;
    private javax.swing.JButton cekPembayaranButton;
    private javax.swing.JButton cekPerizinanButton;
    private javax.swing.JLabel gambarHewanSiapJual;
    private javax.swing.JLabel gambarHewanSiapJual1;
    private javax.swing.JLabel gambarJumlahHewan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judulHewanButuhTindakan;
    private javax.swing.JLabel judulHewanSiapJual;
    private javax.swing.JLabel judulJumlahHewan;
    private javax.swing.JLabel judulTotalPengeluaran;
    private javax.swing.JLabel jumlahPenghuniLabel;
    private javax.swing.JButton kelolaAdminButton;
    private javax.swing.JButton kontakPentingButton;
    private javax.swing.JButton listPenghuniButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelHewanButuhTindakan;
    private javax.swing.JPanel panelHewanSiapJual;
    private javax.swing.JPanel panelJumlahHewan;
    private javax.swing.JPanel panelTotalPengeluaran;
    private javax.swing.JButton pelaporanButton;
    private javax.swing.JLabel pelaporanMasukLabel;
    private javax.swing.JLabel pembayaranBaruLabel;
    private javax.swing.JLabel perizinanMasukLabel;
    // End of variables declaration//GEN-END:variables
}
