/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simpurna.view;

import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.ToolTipManager;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import simpurna.config.Database;
import simpurna.controller.PembayaranController;
import simpurna.controller.PengumumanController;
import simpurna.controller.PerizinanController;
import simpurna.model.Session;
import simpurna.observer.Observer;
import java.sql.*;
import simpurna.controller.LaporanController;

/**
 *
 * @author alfia
 */
public class DashboardRenter extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form DashboardRenter
     */
    PengumumanController pengumumanController = new PengumumanController();
    PembayaranController pembayaranController = new PembayaranController();
    PerizinanController perizinanController = new PerizinanController();
    LaporanController laporanController = new LaporanController();
    String uname;
    
    public DashboardRenter() {
        initComponents();
        pengumumanController.registerObserver(this);
        updatePengumuman();
        pembayaranController.countSuccessfulPayments(this);
        perizinanController.countByUsername(this);
        laporanController.countTotalPelaporan(this);
        Session session = Session.getInstance();
        uname = session.getUsername();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDashboard = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        kontakPentingButton = new javax.swing.JButton();
        pembayaranButton = new javax.swing.JButton();
        perizinanButton = new javax.swing.JButton();
        cekPengumumanButton = new javax.swing.JButton();
        pelaporanButton = new javax.swing.JButton();
        cetakBuktiPembayaran = new javax.swing.JButton();
        panelPengumuman = new javax.swing.JPanel();
        judulPengumuman = new javax.swing.JLabel();
        totalPengumumanLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelLaporanSaya = new javax.swing.JPanel();
        judulHewanSiapJual = new javax.swing.JLabel();
        gambarHewanSiapJual = new javax.swing.JLabel();
        pengajuanPerizinanLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pembayaranSaya = new javax.swing.JPanel();
        judulHewanButuhTindakan = new javax.swing.JLabel();
        gambarHewanSiapJual1 = new javax.swing.JLabel();
        pembayaranBerhasilLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelPelaporan = new javax.swing.JPanel();
        judulPelaporan = new javax.swing.JLabel();
        gambarJumlahHewan1 = new javax.swing.JLabel();
        totalPelaporanLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDashboard.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelDashboard.setPreferredSize(new java.awt.Dimension(209, 500));

        judul.setFont(new java.awt.Font("Cooper Black", 1, 23)); // NOI18N
        judul.setText("siMPURNA");

        kontakPentingButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kontakPentingButton.setText("KONTAK PENTING");
        kontakPentingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kontakPentingButton.setMaximumSize(new java.awt.Dimension(146, 26));
        kontakPentingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontakPentingButtonActionPerformed(evt);
            }
        });

        pembayaranButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pembayaranButton.setText("PEMBAYARAN");
        pembayaranButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pembayaranButton.setMaximumSize(new java.awt.Dimension(146, 26));
        pembayaranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranButtonActionPerformed(evt);
            }
        });

        perizinanButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        perizinanButton.setText("PERIZINAN");
        perizinanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perizinanButton.setMaximumSize(new java.awt.Dimension(146, 26));
        perizinanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perizinanButtonActionPerformed(evt);
            }
        });

        cekPengumumanButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cekPengumumanButton.setText("CEK PENGUMUMAN");
        cekPengumumanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cekPengumumanButton.setMaximumSize(new java.awt.Dimension(146, 26));
        cekPengumumanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekPengumumanButtonActionPerformed(evt);
            }
        });

        pelaporanButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pelaporanButton.setText("PELAPORAN");
        pelaporanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pelaporanButton.setMaximumSize(new java.awt.Dimension(146, 26));
        pelaporanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelaporanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kontakPentingButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pembayaranButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(perizinanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cekPengumumanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pelaporanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pembayaranButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kontakPentingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(perizinanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cekPengumumanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pelaporanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 209, 510));

        cetakBuktiPembayaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cetakBuktiPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/print.png"))); // NOI18N
        cetakBuktiPembayaran.setText("Bukti Pembayaran");
        cetakBuktiPembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cetakBuktiPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakBuktiPembayaranActionPerformed(evt);
            }
        });
        add(cetakBuktiPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 210, 50));

        panelPengumuman.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelPengumuman.setForeground(new java.awt.Color(255, 255, 255));
        panelPengumuman.setPreferredSize(new java.awt.Dimension(277, 199));

        judulPengumuman.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulPengumuman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulPengumuman.setText("Pengumuman");

        totalPengumumanLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        totalPengumumanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPengumumanLabel.setText("56");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/annoucenment.png"))); // NOI18N

        javax.swing.GroupLayout panelPengumumanLayout = new javax.swing.GroupLayout(panelPengumuman);
        panelPengumuman.setLayout(panelPengumumanLayout);
        panelPengumumanLayout.setHorizontalGroup(
            panelPengumumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPengumumanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPengumumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPengumumanLayout.createSequentialGroup()
                        .addComponent(judulPengumuman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPengumumanLayout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addGroup(panelPengumumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPengumumanLayout.createSequentialGroup()
                                .addComponent(totalPengumumanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPengumumanLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))))))
        );
        panelPengumumanLayout.setVerticalGroup(
            panelPengumumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPengumumanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(judulPengumuman, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPengumumanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelPengumuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, 190));

        panelLaporanSaya.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelLaporanSaya.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        panelLaporanSaya.setPreferredSize(new java.awt.Dimension(277, 199));

        judulHewanSiapJual.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulHewanSiapJual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulHewanSiapJual.setText("Pengajuan Perizinan");
        judulHewanSiapJual.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        pengajuanPerizinanLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        pengajuanPerizinanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pengajuanPerizinanLabel.setText("07");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/izin.png"))); // NOI18N

        javax.swing.GroupLayout panelLaporanSayaLayout = new javax.swing.GroupLayout(panelLaporanSaya);
        panelLaporanSaya.setLayout(panelLaporanSayaLayout);
        panelLaporanSayaLayout.setHorizontalGroup(
            panelLaporanSayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judulHewanSiapJual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelLaporanSayaLayout.createSequentialGroup()
                .addGroup(panelLaporanSayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLaporanSayaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gambarHewanSiapJual)
                        .addGap(69, 69, 69)
                        .addComponent(pengajuanPerizinanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLaporanSayaLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        panelLaporanSayaLayout.setVerticalGroup(
            panelLaporanSayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanSayaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(judulHewanSiapJual)
                .addGroup(panelLaporanSayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLaporanSayaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(gambarHewanSiapJual))
                    .addGroup(panelLaporanSayaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pengajuanPerizinanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(panelLaporanSaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 270, -1));

        pembayaranSaya.setBackground(new java.awt.Color(249, 251, 231, 199));
        pembayaranSaya.setPreferredSize(new java.awt.Dimension(277, 134));

        judulHewanButuhTindakan.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulHewanButuhTindakan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulHewanButuhTindakan.setText("Pembayaran Berhasil");

        pembayaranBerhasilLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        pembayaranBerhasilLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pembayaranBerhasilLabel.setText("01");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/pembayaran.png"))); // NOI18N

        javax.swing.GroupLayout pembayaranSayaLayout = new javax.swing.GroupLayout(pembayaranSaya);
        pembayaranSaya.setLayout(pembayaranSayaLayout);
        pembayaranSayaLayout.setHorizontalGroup(
            pembayaranSayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pembayaranSayaLayout.createSequentialGroup()
                .addGroup(pembayaranSayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pembayaranSayaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(judulHewanButuhTindakan, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                    .addGroup(pembayaranSayaLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pembayaranSayaLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(pembayaranBerhasilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pembayaranSayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pembayaranSayaLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(gambarHewanSiapJual1)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );
        pembayaranSayaLayout.setVerticalGroup(
            pembayaranSayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pembayaranSayaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judulHewanButuhTindakan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pembayaranBerhasilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(22, 22, 22))
            .addGroup(pembayaranSayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pembayaranSayaLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(gambarHewanSiapJual1)
                    .addContainerGap(145, Short.MAX_VALUE)))
        );

        add(pembayaranSaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 270, 190));

        panelPelaporan.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelPelaporan.setForeground(new java.awt.Color(255, 255, 255));
        panelPelaporan.setPreferredSize(new java.awt.Dimension(277, 199));

        judulPelaporan.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulPelaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulPelaporan.setText("Pelaporan");

        totalPelaporanLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        totalPelaporanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPelaporanLabel.setText("56");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/complaint.png"))); // NOI18N

        javax.swing.GroupLayout panelPelaporanLayout = new javax.swing.GroupLayout(panelPelaporan);
        panelPelaporan.setLayout(panelPelaporanLayout);
        panelPelaporanLayout.setHorizontalGroup(
            panelPelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPelaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPelaporanLayout.createSequentialGroup()
                        .addComponent(judulPelaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelPelaporanLayout.createSequentialGroup()
                        .addComponent(gambarJumlahHewan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPelaporanLayout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addComponent(totalPelaporanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        panelPelaporanLayout.setVerticalGroup(
            panelPelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPelaporanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(judulPelaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPelaporanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelPelaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPelaporanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(gambarJumlahHewan1))
                    .addGroup(panelPelaporanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(panelPelaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/logout.png"))); // NOI18N
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 50, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/background.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void cetakBuktiPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakBuktiPembayaranActionPerformed
        // TODO add your handling code here:
        try {
            Database database = Database.getInstance();
            Connection conn = database.getConnection();
            HashMap parameter = new HashMap<>();
            parameter.put("username", uname);
            JasperDesign jdesign = JRXmlLoader.load("D:\\\\KULIAH\\\\SMT 4\\\\PBO\\\\2ks1-222112218-simpurna\\\\src\\\\simpurna\\\\view\\\\laporan_pembayaran.jrxml");

            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, parameter, conn);
            JasperViewer.viewReport(jprint);

         } catch(Exception e) {
             System.out.println(e.getMessage());
         }
    }//GEN-LAST:event_cetakBuktiPembayaranActionPerformed

    private void pelaporanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelaporanButtonActionPerformed
        // TODO add your handling code here:
        LaporanRenter lr = new LaporanRenter();

        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(lr);

        parentWindow.pack();

        parentWindow.setLocationRelativeTo(null);

        lr.setVisible(true);

    }//GEN-LAST:event_pelaporanButtonActionPerformed

    private void cekPengumumanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekPengumumanButtonActionPerformed
        // TODO add your handling code here:
        PengumumanRenter pr = new PengumumanRenter();

        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(pr);

        parentWindow.pack();

        parentWindow.setLocationRelativeTo(null);

        pr.setVisible(true);
    }//GEN-LAST:event_cekPengumumanButtonActionPerformed

    private void perizinanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perizinanButtonActionPerformed
        // TODO add your handling code here:
        PerizinanRenter pr = new PerizinanRenter();

        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(pr);

        parentWindow.pack();

        parentWindow.setLocationRelativeTo(null);

        pr.setVisible(true);
    }//GEN-LAST:event_perizinanButtonActionPerformed

    private void pembayaranButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranButtonActionPerformed
        // TODO add your handling code here:
        Pembayaran p = new Pembayaran();

        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(p);

        parentWindow.pack();

        parentWindow.setLocationRelativeTo(null);

        p.setVisible(true);
    }//GEN-LAST:event_pembayaranButtonActionPerformed

    private void kontakPentingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontakPentingButtonActionPerformed
        // TODO add your handling code here:
        KontakPenting kp = new KontakPenting();

        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(kp);

        parentWindow.pack();

        parentWindow.setLocationRelativeTo(null);

        kp.setVisible(true);

    }//GEN-LAST:event_kontakPentingButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        Session session = Session.getInstance();
        session.clearSession();
        
        Login login = new Login();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.setVisible(false);
        
        login.setVisible(true);
        
        login.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        // TODO add your handling code here:
        JButton button = (JButton) evt.getSource();
        button.setToolTipText("Keluar");
        ToolTipManager.sharedInstance().setInitialDelay(0);
    }//GEN-LAST:event_logoutButtonMouseEntered
    
    public JLabel getPengajuanPerizinan() {
        return pengajuanPerizinanLabel;
    }
    
    public JLabel getTotalPengumuman() {
        return totalPengumumanLabel;
    }
    
    public JLabel getTotalPembayaranSuccess() {
        return pembayaranBerhasilLabel;
    }
    
    public JLabel getTotalPelaporan() {
        return totalPelaporanLabel;
    }
    
    @Override
    public void updatePengumuman() {
       pengumumanController.countTotalPengumuman(this);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekPengumumanButton;
    private javax.swing.JButton cetakBuktiPembayaran;
    private javax.swing.JLabel gambarHewanSiapJual;
    private javax.swing.JLabel gambarHewanSiapJual1;
    private javax.swing.JLabel gambarJumlahHewan1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judulHewanButuhTindakan;
    private javax.swing.JLabel judulHewanSiapJual;
    private javax.swing.JLabel judulPelaporan;
    private javax.swing.JLabel judulPengumuman;
    private javax.swing.JButton kontakPentingButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelLaporanSaya;
    private javax.swing.JPanel panelPelaporan;
    private javax.swing.JPanel panelPengumuman;
    private javax.swing.JButton pelaporanButton;
    private javax.swing.JLabel pembayaranBerhasilLabel;
    private javax.swing.JButton pembayaranButton;
    private javax.swing.JPanel pembayaranSaya;
    private javax.swing.JLabel pengajuanPerizinanLabel;
    private javax.swing.JButton perizinanButton;
    private javax.swing.JLabel totalPelaporanLabel;
    private javax.swing.JLabel totalPengumumanLabel;
    // End of variables declaration//GEN-END:variables


}
