/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simpurna.view;

import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import simpurna.controller.KontakPentingController;

/**
 *
 * @author alfia
 */
public class KontakPenting extends javax.swing.JPanel {

    /**
     * Creates new form KontakPenting
     */
    KontakPentingController kpc = new KontakPentingController();
    public KontakPenting() {
        initComponents();
        kpc.displayAllInRenter(this);
    }
    
    public JTable getKontakPentingTable(){
        return kontakPentingTable;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        daftarKontakPenting = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kontakPentingTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daftarKontakPenting.setBackground(new java.awt.Color(249, 251, 231, 199));
        daftarKontakPenting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kontakPentingTable.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kontakPentingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Kontak", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kontakPentingTable.setRowHeight(30);
        jScrollPane1.setViewportView(kontakPentingTable);

        daftarKontakPenting.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 790, 300));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Daftar Kontak Penting");
        daftarKontakPenting.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 790, 50));

        add(daftarKontakPenting, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 830, 380));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/home.png"))); // NOI18N
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 910, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        DashboardRenter dr = new DashboardRenter();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(dr);

        parentWindow.pack();

        dr.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel daftarKontakPenting;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kontakPentingTable;
    // End of variables declaration//GEN-END:variables
}
