/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simpurna.view;

import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import simpurna.controller.LaporanController;

/**
 *
 * @author alfia
 */
public class LaporanAdmin extends javax.swing.JPanel {

    /**
     * Creates new form LaporanAdmin
     */
    LaporanController lc = new LaporanController();
    public LaporanAdmin() {
        initComponents();
        lc.displayLaporanAll(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormJual = new javax.swing.JPanel();
        judulPenjualanHewan = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        labelTanggapan = new javax.swing.JLabel();
        tambahButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tanggapanTextArea = new javax.swing.JTextArea();
        labelCaraPenjualan1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelCaraPenjualan2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        isiLaporanTextArea = new javax.swing.JTextArea();
        panelHewanSiapJual = new javax.swing.JPanel();
        judulHewanSiapJual = new javax.swing.JLabel();
        jScrollHewanSiapJual = new javax.swing.JScrollPane();
        laporanAdminTable = new javax.swing.JTable();
        homeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFormJual.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelFormJual.setPreferredSize(new java.awt.Dimension(277, 134));

        judulPenjualanHewan.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulPenjualanHewan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulPenjualanHewan.setText("TANGGAPI LAPORAN");

        idTextField.setPreferredSize(new java.awt.Dimension(71, 24));

        labelTanggapan.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelTanggapan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTanggapan.setText("Tanggapan");

        tambahButton.setBackground(new java.awt.Color(204, 204, 204));
        tambahButton.setText("SUBMIT");
        tambahButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        tanggapanTextArea.setColumns(20);
        tanggapanTextArea.setRows(5);
        tanggapanTextArea.setLineWrap(true);
        tanggapanTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tanggapanTextArea);

        labelCaraPenjualan1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelCaraPenjualan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCaraPenjualan1.setText("Id Laporan");

        labelCaraPenjualan2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelCaraPenjualan2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCaraPenjualan2.setText("Isi Laporan");

        isiLaporanTextArea.setColumns(20);
        isiLaporanTextArea.setRows(5);
        isiLaporanTextArea.setLineWrap(true);
        isiLaporanTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(isiLaporanTextArea);

        javax.swing.GroupLayout panelFormJualLayout = new javax.swing.GroupLayout(panelFormJual);
        panelFormJual.setLayout(panelFormJualLayout);
        panelFormJualLayout.setHorizontalGroup(
            panelFormJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormJualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulPenjualanHewan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelFormJualLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelFormJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormJualLayout.createSequentialGroup()
                        .addGroup(panelFormJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCaraPenjualan2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTanggapan, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCaraPenjualan1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormJualLayout.createSequentialGroup()
                        .addGroup(panelFormJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelFormJualLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tambahButton))
                            .addGroup(panelFormJualLayout.createSequentialGroup()
                                .addGroup(panelFormJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFormJualLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(idTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18))))
        );
        panelFormJualLayout.setVerticalGroup(
            panelFormJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormJualLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(judulPenjualanHewan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCaraPenjualan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelFormJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFormJualLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelFormJualLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelCaraPenjualan2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addComponent(labelTanggapan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tambahButton)
                .addGap(64, 64, 64))
        );

        add(panelFormJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 290, 390));

        panelHewanSiapJual.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelHewanSiapJual.setPreferredSize(new java.awt.Dimension(277, 134));

        judulHewanSiapJual.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulHewanSiapJual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulHewanSiapJual.setText("DAFTAR LAPORAN");

        laporanAdminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Pelapor", "Tgl Laporan", "Isi Laporan", "Tanggapan", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        laporanAdminTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanAdminTable.setRowHeight(30);
        laporanAdminTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanAdminTableMouseClicked(evt);
            }
        });
        jScrollHewanSiapJual.setViewportView(laporanAdminTable);

        javax.swing.GroupLayout panelHewanSiapJualLayout = new javax.swing.GroupLayout(panelHewanSiapJual);
        panelHewanSiapJual.setLayout(panelHewanSiapJualLayout);
        panelHewanSiapJualLayout.setHorizontalGroup(
            panelHewanSiapJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHewanSiapJualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulHewanSiapJual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHewanSiapJualLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollHewanSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelHewanSiapJualLayout.setVerticalGroup(
            panelHewanSiapJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHewanSiapJualLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(judulHewanSiapJual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollHewanSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        add(panelHewanSiapJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 520, 390));

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/home.png"))); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        //         TODO add your handling code here:
       lc.updateTanggapan(this);
       lc.displayLaporanAll(this);
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void laporanAdminTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanAdminTableMouseClicked
        // TODO add your handling code here:
        int row = laporanAdminTable.getSelectedRow();
        String id = laporanAdminTable.getValueAt(row, 0).toString();
        String isi = laporanAdminTable.getValueAt(row, 3).toString();
        String tanggapan = laporanAdminTable.getValueAt(row, 4).toString();
        idTextField.setText(id);
        isiLaporanTextArea.setText(isi);
        tanggapanTextArea.setText(tanggapan);
    }//GEN-LAST:event_laporanAdminTableMouseClicked

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        DashboardAdmin da = new DashboardAdmin();

        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(da);

        parentWindow.pack();

        da.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed
    
    public JTable getLaporanAdminTable() {
       return laporanAdminTable;
    }
    
    public JTextField getId() {
        return idTextField;
    }
    
    public JTextArea getTanggapan() {
        return tanggapanTextArea;
    }
    
    public JTextArea getIsi() {
        return isiLaporanTextArea;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JTextArea isiLaporanTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollHewanSiapJual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judulHewanSiapJual;
    private javax.swing.JLabel judulPenjualanHewan;
    private javax.swing.JLabel labelCaraPenjualan1;
    private javax.swing.JLabel labelCaraPenjualan2;
    private javax.swing.JLabel labelTanggapan;
    private javax.swing.JTable laporanAdminTable;
    private javax.swing.JPanel panelFormJual;
    private javax.swing.JPanel panelHewanSiapJual;
    private javax.swing.JButton tambahButton;
    private javax.swing.JTextArea tanggapanTextArea;
    // End of variables declaration//GEN-END:variables
}
