/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simpurna.view;

import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import simpurna.controller.PembayaranController;

/**
 *
 * @author alfia
 */
public class PembayaranAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PembayaranAdmin
     */
    PembayaranController pembayaranController = new PembayaranController();
    
    public PembayaranAdmin() {
        initComponents();
        pembayaranController.displayTableNeedConfirmAdmin(this);
        pembayaranController.displayTableSuccessAdmin(this);
        pembayaranController.setTotalPembayaranSukses(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        needConfirmPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        perluKonfirmTable = new javax.swing.JTable();
        konfirmButton = new javax.swing.JButton();
        pembayaranSuksesPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        suksesTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        totalPembayaranSukses = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        needConfirmPanel.setBackground(new java.awt.Color(249, 251, 231, 199));
        needConfirmPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pembayaran Perlu Konfirmasi");
        needConfirmPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 400, 40));

        perluKonfirmTable.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        perluKonfirmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Bayar", "Username", "Rek. Tujuan", "Tanggal", "Total Bayar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        perluKonfirmTable.setRowHeight(30);
        perluKonfirmTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perluKonfirmTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(perluKonfirmTable);

        needConfirmPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 380, 250));

        konfirmButton.setText("Konfirmasi");
        konfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmButtonActionPerformed(evt);
            }
        });
        needConfirmPanel.add(konfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        add(needConfirmPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 420, 340));

        pembayaranSuksesPanel.setBackground(new java.awt.Color(249, 251, 231, 199));
        pembayaranSuksesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id ", "Jenis ", "Tipe Pengeluaran", "Jumlah perlakuan", "Harga", "Total "
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pembayaranSuksesPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 380, 240));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id ", "Jenis ", "Tipe Pengeluaran", "Jumlah perlakuan", "Harga", "Total "
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        pembayaranSuksesPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 380, 240));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id ", "Jenis ", "Tipe Pengeluaran", "Jumlah perlakuan", "Harga", "Total "
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        pembayaranSuksesPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 380, 240));

        suksesTable.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        suksesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID bayar", "Username", "Rek. Tujuan", "Tanggal", "Total Bayar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        suksesTable.setRowHeight(30);
        jScrollPane6.setViewportView(suksesTable);

        pembayaranSuksesPanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 380, 250));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pembayaran Sukses");
        pembayaranSuksesPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 400, 40));

        totalPembayaranSukses.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pembayaranSuksesPanel.add(totalPembayaranSukses, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 330, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jLabel9.setText("Total :");
        pembayaranSuksesPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 60, 20));

        add(pembayaranSuksesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 420, 340));

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/home.png"))); // NOI18N
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 60, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 900, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void perluKonfirmTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perluKonfirmTableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_perluKonfirmTableMouseClicked

    private void konfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmButtonActionPerformed
        // TODO add your handling code here:
        pembayaranController.confirmPembayaran(this);
        pembayaranController.displayTableNeedConfirmAdmin(this);
        pembayaranController.displayTableSuccessAdmin(this);
        pembayaranController.setTotalPembayaranSukses(this);
    }//GEN-LAST:event_konfirmButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        DashboardAdmin da = new DashboardAdmin();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(da);

        parentWindow.pack();

        da.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed
    
    public JTable getNeedConfirmTable() {
        return perluKonfirmTable;
    }
    
    public JTable getSuccessTable() {
        return suksesTable;
    }
    
    public JTextField getTotalTextField() {
        return totalPembayaranSukses;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JButton konfirmButton;
    private javax.swing.JPanel needConfirmPanel;
    private javax.swing.JPanel pembayaranSuksesPanel;
    private javax.swing.JTable perluKonfirmTable;
    private javax.swing.JTable suksesTable;
    private javax.swing.JTextField totalPembayaranSukses;
    // End of variables declaration//GEN-END:variables
}
