/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simpurna.view;

import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import simpurna.controller.PengumumanController;
import simpurna.model.Session;

/**
 *
 * @author alfia
 */
public class PengumumanAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PengumumanAdmin
     */
    String username;
    Integer id;
    PengumumanController pc = new PengumumanController();
    public PengumumanAdmin() {
        initComponents();
        setUsername();
        pc.displayAllPengumumanAdmin(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormBuatPerizinan = new javax.swing.JPanel();
        judulPenjualanHewan = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        labelIdHewan2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pengumumanTextArea = new javax.swing.JTextArea();
        panelRincianPerizinan = new javax.swing.JPanel();
        judulHewanSiapJual = new javax.swing.JLabel();
        jScrollHewanSiapJual = new javax.swing.JScrollPane();
        pengumumanTable = new javax.swing.JTable();
        editButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFormBuatPerizinan.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelFormBuatPerizinan.setPreferredSize(new java.awt.Dimension(277, 134));

        judulPenjualanHewan.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        judulPenjualanHewan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulPenjualanHewan.setText("Buat Pengumuman");

        submitButton.setBackground(new java.awt.Color(204, 204, 204));
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/add.png"))); // NOI18N
        submitButton.setText("TAMBAH");
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        labelIdHewan2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelIdHewan2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelIdHewan2.setText("Isi Pengumuman");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/annoucenment.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/annoucenment.png"))); // NOI18N

        pengumumanTextArea.setColumns(20);
        pengumumanTextArea.setRows(5);
        pengumumanTextArea.setPreferredSize(new java.awt.Dimension(230, 100));
        pengumumanTextArea.setLineWrap(true);
        pengumumanTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(pengumumanTextArea);

        javax.swing.GroupLayout panelFormBuatPerizinanLayout = new javax.swing.GroupLayout(panelFormBuatPerizinan);
        panelFormBuatPerizinan.setLayout(panelFormBuatPerizinanLayout);
        panelFormBuatPerizinanLayout.setHorizontalGroup(
            panelFormBuatPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormBuatPerizinanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelFormBuatPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormBuatPerizinanLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(judulPenjualanHewan, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(labelIdHewan2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFormBuatPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(submitButton)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelFormBuatPerizinanLayout.setVerticalGroup(
            panelFormBuatPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormBuatPerizinanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelFormBuatPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFormBuatPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(judulPenjualanHewan)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(labelIdHewan2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(submitButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        add(panelFormBuatPerizinan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 290, 390));

        panelRincianPerizinan.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelRincianPerizinan.setPreferredSize(new java.awt.Dimension(277, 134));

        judulHewanSiapJual.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulHewanSiapJual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulHewanSiapJual.setText("Data Pengumuman");

        pengumumanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Isi Pengumuman", "Pembuat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pengumumanTable.setRowHeight(30);
        pengumumanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengumumanTableMouseClicked(evt);
            }
        });
        jScrollHewanSiapJual.setViewportView(pengumumanTable);

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/edit.png"))); // NOI18N
        editButton.setText("EDIT");
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        hapusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/delete.png"))); // NOI18N
        hapusButton.setText("HAPUS");
        hapusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRincianPerizinanLayout = new javax.swing.GroupLayout(panelRincianPerizinan);
        panelRincianPerizinan.setLayout(panelRincianPerizinanLayout);
        panelRincianPerizinanLayout.setHorizontalGroup(
            panelRincianPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincianPerizinanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRincianPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRincianPerizinanLayout.createSequentialGroup()
                        .addComponent(judulHewanSiapJual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRincianPerizinanLayout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(panelRincianPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelRincianPerizinanLayout.createSequentialGroup()
                                .addComponent(hapusButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editButton))
                            .addComponent(jScrollHewanSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );
        panelRincianPerizinanLayout.setVerticalGroup(
            panelRincianPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincianPerizinanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(judulHewanSiapJual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollHewanSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRincianPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusButton)
                    .addComponent(editButton))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        add(panelRincianPerizinan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 520, 390));

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/home.png"))); // NOI18N
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //         TODO add your handling code here:
        pc.insert(this);
        pc.displayAllPengumumanAdmin(this);
       
    }//GEN-LAST:event_submitButtonActionPerformed

    private void pengumumanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengumumanTableMouseClicked
        // TODO add your handling code here:
        int row = pengumumanTable.getSelectedRow();
        String isi = pengumumanTable.getValueAt(row, 2).toString();
        
        pengumumanTextArea.setText(isi);
        this.id = (Integer) pengumumanTable.getValueAt(row, 0);
    }//GEN-LAST:event_pengumumanTableMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        pc.edit(this);
        pc.displayAllPengumumanAdmin(this);
    }//GEN-LAST:event_editButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        pc.delete(this);
        pc.displayAllPengumumanAdmin(this);
        pengumumanTextArea.setText("");
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        DashboardAdmin da = new DashboardAdmin();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(da);

        parentWindow.pack();

        da.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed
    
    private void setUsername() {
        Session session = Session.getInstance();
        String uname = session.getUsername();
        username = uname;
    }
    
    public String getUsername() {
        return username;
    }
    
    public JTable getPengumumanTable() {
        return pengumumanTable;
    }
    
    public JTextArea getIsi() {
        return pengumumanTextArea;
    }
    
    public Integer getId() {
        return id;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollHewanSiapJual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulHewanSiapJual;
    private javax.swing.JLabel judulPenjualanHewan;
    private javax.swing.JLabel labelIdHewan2;
    private javax.swing.JPanel panelFormBuatPerizinan;
    private javax.swing.JPanel panelRincianPerizinan;
    private javax.swing.JTable pengumumanTable;
    private javax.swing.JTextArea pengumumanTextArea;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
