/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simpurna.view;

import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import simpurna.controller.PerizinanController;

/**
 *
 * @author alfia
 */
public class PerizinanAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PerizinanAdmin
     */
    PerizinanController pc = new PerizinanController();
    public PerizinanAdmin() {
        initComponents();
        pc.displayPerizinanMasukAdmin(this);
        pc.displayAllConfirmedPerizinan(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRincian1 = new javax.swing.JPanel();
        judulRincian1 = new javax.swing.JLabel();
        jScrollRincian1 = new javax.swing.JScrollPane();
        perizinanDikonfirmTable = new javax.swing.JTable();
        panelRincian3 = new javax.swing.JPanel();
        judulRincian5 = new javax.swing.JLabel();
        jScrollRincian3 = new javax.swing.JScrollPane();
        perizinanMasukTable = new javax.swing.JTable();
        setujuiButton = new javax.swing.JButton();
        tolakButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRincian1.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelRincian1.setPreferredSize(new java.awt.Dimension(277, 134));

        judulRincian1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulRincian1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulRincian1.setText("Perizinan Dikonfirmasi");

        perizinanDikonfirmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Perizinan", "Username", "Keterangan", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        perizinanDikonfirmTable.setRowHeight(30);
        perizinanDikonfirmTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perizinanDikonfirmTableMouseClicked(evt);
            }
        });
        jScrollRincian1.setViewportView(perizinanDikonfirmTable);

        javax.swing.GroupLayout panelRincian1Layout = new javax.swing.GroupLayout(panelRincian1);
        panelRincian1.setLayout(panelRincian1Layout);
        panelRincian1Layout.setHorizontalGroup(
            panelRincian1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincian1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulRincian1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelRincian1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollRincian1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        panelRincian1Layout.setVerticalGroup(
            panelRincian1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincian1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(judulRincian1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollRincian1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(panelRincian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 360, 370));

        panelRincian3.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelRincian3.setPreferredSize(new java.awt.Dimension(277, 134));

        judulRincian5.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulRincian5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulRincian5.setText("Perizinan Masuk");

        perizinanMasukTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Perizinan", "Username", "Pelaksanaan", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        perizinanMasukTable.setRowHeight(30);
        perizinanMasukTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perizinanMasukTableMouseClicked(evt);
            }
        });
        jScrollRincian3.setViewportView(perizinanMasukTable);

        setujuiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/check.png"))); // NOI18N
        setujuiButton.setText("SETUJU");
        setujuiButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setujuiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setujuiButtonActionPerformed(evt);
            }
        });

        tolakButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/no.png"))); // NOI18N
        tolakButton.setText("TOLAK");
        tolakButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tolakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tolakButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRincian3Layout = new javax.swing.GroupLayout(panelRincian3);
        panelRincian3.setLayout(panelRincian3Layout);
        panelRincian3Layout.setHorizontalGroup(
            panelRincian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincian3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulRincian5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelRincian3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(panelRincian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollRincian3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRincian3Layout.createSequentialGroup()
                        .addComponent(tolakButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setujuiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        panelRincian3Layout.setVerticalGroup(
            panelRincian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincian3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(judulRincian5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollRincian3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRincian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setujuiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tolakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelRincian3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 370, 370));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/home.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void perizinanDikonfirmTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perizinanDikonfirmTableMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_perizinanDikonfirmTableMouseClicked

    private void perizinanMasukTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perizinanMasukTableMouseClicked
        // TODO add your handling code here:
       

    }//GEN-LAST:event_perizinanMasukTableMouseClicked

    private void setujuiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setujuiButtonActionPerformed
        // TODO add your handling code here:
        pc.setujuiPerizinan(this);
        pc.displayPerizinanMasukAdmin(this);
        pc.displayAllConfirmedPerizinan(this);
    }//GEN-LAST:event_setujuiButtonActionPerformed

    private void tolakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tolakButtonActionPerformed
        // TODO add your handling code here:
        pc.tolakPerizinan(this);
        pc.displayPerizinanMasukAdmin(this);
        pc.displayAllConfirmedPerizinan(this);
    }//GEN-LAST:event_tolakButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DashboardAdmin da = new DashboardAdmin();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(da);

        parentWindow.pack();

        da.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public JTable getPerizinanMasuk() {
        return perizinanMasukTable;
    }
    
    public JTable getPerizinanDiConfirm() {
        return perizinanDikonfirmTable;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollRincian1;
    private javax.swing.JScrollPane jScrollRincian3;
    private javax.swing.JLabel judulRincian1;
    private javax.swing.JLabel judulRincian5;
    private javax.swing.JPanel panelRincian1;
    private javax.swing.JPanel panelRincian3;
    private javax.swing.JTable perizinanDikonfirmTable;
    private javax.swing.JTable perizinanMasukTable;
    private javax.swing.JButton setujuiButton;
    private javax.swing.JButton tolakButton;
    // End of variables declaration//GEN-END:variables
}
