/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simpurna.view;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.JTableHeader;
import simpurna.controller.PerizinanController;
import simpurna.model.Session;

/**
 *
 * @author alfia
 */
public class PerizinanRenter extends javax.swing.JPanel {

    /**
     * Creates new form PerizinanRenter
     */
    PerizinanController pc = new PerizinanController();
    String username;
    
    public PerizinanRenter() {
        initComponents();
        setUsername();
        pc.displayByUsername(this);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormBuatPerizinan = new javax.swing.JPanel();
        judulPenjualanHewan = new javax.swing.JLabel();
        labelIdHewan = new javax.swing.JLabel();
        labelCaraPenjualan = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        labelIdHewan1 = new javax.swing.JLabel();
        tanggalPelaksanaan = new com.toedter.calendar.JDateChooser();
        keteranganTextField = new javax.swing.JTextField();
        waktuSpinner = new javax.swing.JSpinner();
        labelIdHewan2 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        panelRincianPerizinan = new javax.swing.JPanel();
        judulHewanSiapJual = new javax.swing.JLabel();
        jScrollHewanSiapJual = new javax.swing.JScrollPane();
        rincianPerizinanTable = new javax.swing.JTable();
        homeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFormBuatPerizinan.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelFormBuatPerizinan.setPreferredSize(new java.awt.Dimension(277, 134));

        judulPenjualanHewan.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulPenjualanHewan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulPenjualanHewan.setText("Ajukan Perizinan");

        labelIdHewan.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelIdHewan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelIdHewan.setText("Tanggal Pelaksanaan");

        labelCaraPenjualan.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelCaraPenjualan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCaraPenjualan.setText("Waktu Pelaksanaan (Jam)");

        submitButton.setBackground(new java.awt.Color(204, 204, 204));
        submitButton.setText("SUBMIT");
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        labelIdHewan1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelIdHewan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelIdHewan1.setText("Keterangan Izin");

        tanggalPelaksanaan.setPreferredSize(new java.awt.Dimension(88, 26));

        keteranganTextField.setMinimumSize(new java.awt.Dimension(64, 26));

        waktuSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", "24:00"}));
        waktuSpinner.setMinimumSize(new java.awt.Dimension(64, 26));
        waktuSpinner.setPreferredSize(new java.awt.Dimension(64, 26));

        labelIdHewan2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        labelIdHewan2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelIdHewan2.setText("Username");

        usernameTextField.setMinimumSize(new java.awt.Dimension(64, 26));

        javax.swing.GroupLayout panelFormBuatPerizinanLayout = new javax.swing.GroupLayout(panelFormBuatPerizinan);
        panelFormBuatPerizinan.setLayout(panelFormBuatPerizinanLayout);
        panelFormBuatPerizinanLayout.setHorizontalGroup(
            panelFormBuatPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormBuatPerizinanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulPenjualanHewan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelFormBuatPerizinanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelFormBuatPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormBuatPerizinanLayout.createSequentialGroup()
                        .addComponent(labelIdHewan2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormBuatPerizinanLayout.createSequentialGroup()
                        .addGroup(panelFormBuatPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(waktuSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(keteranganTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tanggalPelaksanaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelFormBuatPerizinanLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(submitButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFormBuatPerizinanLayout.createSequentialGroup()
                                .addGroup(panelFormBuatPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCaraPenjualan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIdHewan1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIdHewan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 85, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))))
        );
        panelFormBuatPerizinanLayout.setVerticalGroup(
            panelFormBuatPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormBuatPerizinanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(judulPenjualanHewan)
                .addGap(18, 18, 18)
                .addComponent(labelIdHewan2)
                .addGap(7, 7, 7)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIdHewan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keteranganTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelIdHewan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalPelaksanaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCaraPenjualan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waktuSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(submitButton)
                .addGap(46, 46, 46))
        );

        add(panelFormBuatPerizinan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 290, 390));

        panelRincianPerizinan.setBackground(new java.awt.Color(249, 251, 231, 199));
        panelRincianPerizinan.setPreferredSize(new java.awt.Dimension(277, 134));

        judulHewanSiapJual.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        judulHewanSiapJual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulHewanSiapJual.setText("Rincian Perizinan Saya");

        rincianPerizinanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tgl Pengajuan", "Tgl Pelaksanaan", "Waktu ", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rincianPerizinanTable.setRowHeight(30);
        jScrollHewanSiapJual.setViewportView(rincianPerizinanTable);

        javax.swing.GroupLayout panelRincianPerizinanLayout = new javax.swing.GroupLayout(panelRincianPerizinan);
        panelRincianPerizinan.setLayout(panelRincianPerizinanLayout);
        panelRincianPerizinanLayout.setHorizontalGroup(
            panelRincianPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincianPerizinanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulHewanSiapJual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRincianPerizinanLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollHewanSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelRincianPerizinanLayout.setVerticalGroup(
            panelRincianPerizinanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRincianPerizinanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(judulHewanSiapJual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollHewanSiapJual, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        add(panelRincianPerizinan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 520, 390));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/home.png"))); // NOI18N
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpurna/asset/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //         TODO add your handling code here:
        pc.insertPerizinan(this);
        pc.displayByUsername(this);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        DashboardRenter dr = new DashboardRenter();
   
        JFrame parentWindow = (JFrame) SwingUtilities.getWindowAncestor(this);

        parentWindow.getContentPane().remove(this);

        parentWindow.getContentPane().add(dr);

        parentWindow.pack();

        dr.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed
    
    private void setUsername() {
        Session session = Session.getInstance();
        String uname = session.getUsername();
        username = uname;
        usernameTextField.setText(uname);
    }
    
    public JTable getPerizinanTable() {
        return rincianPerizinanTable;
    }
    
    public JTextField getUsernameTextField() {
        return usernameTextField;
    }
    
    public JTextField getKeterangan() {
        return keteranganTextField;
    }
    
    public JDateChooser getTglPelaksanaan() {
        return tanggalPelaksanaan;
    }
    
    public JSpinner getWaktu() {
        return waktuSpinner;
    }

    public String getUsername() {
        return username;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollHewanSiapJual;
    private javax.swing.JLabel judulHewanSiapJual;
    private javax.swing.JLabel judulPenjualanHewan;
    private javax.swing.JTextField keteranganTextField;
    private javax.swing.JLabel labelCaraPenjualan;
    private javax.swing.JLabel labelIdHewan;
    private javax.swing.JLabel labelIdHewan1;
    private javax.swing.JLabel labelIdHewan2;
    private javax.swing.JPanel panelFormBuatPerizinan;
    private javax.swing.JPanel panelRincianPerizinan;
    private javax.swing.JTable rincianPerizinanTable;
    private javax.swing.JButton submitButton;
    private com.toedter.calendar.JDateChooser tanggalPelaksanaan;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JSpinner waktuSpinner;
    // End of variables declaration//GEN-END:variables
}
